const button = document.getElementById('button')
const astro = document.getElementById('astro')
const topo = document.getElementById('top')
const topLeft = document.getElementById('topleft')
const topRight = document.getElementById('topright')
const bottom = document.getElementById('bottom')
const bottomLeft = document.getElementById('bottomleft')
const bottomRight = document.getElementById('bottomright')

const body = document.getElementById('body')
const logo = document.getElementById('logo')
const about = document.getElementById('#about')
const contact = document.getElementById('#contact')
const habilidades = document.getElementById('#habilidades')
const abouth1 = document.getElementById('abouth1')
const abouth2 = document.getElementById('abouth2')
const contacth1 = document.getElementById('contacth1')
const hardh1 = document.getElementById('hardh1')
const header = document.getElementById('header')
const footer = document.getElementById('footer')
const line1 = document.getElementById('line1')
const line2 = document.getElementById('line2')
const line3 = document.getElementById('line3')
const links = document.querySelectorAll('.link')

const local = document.getElementById('local')
const phone = document.getElementById('phone')
const mail = document.getElementById('mail')
const linkedin = document.getElementById('linkedin')
const github = document.getElementById('github')
const instagram = document.getElementById('instagram')

const menuhamburguer = document.getElementById('menu-hamburguer')
const navegacao = document.getElementById('nav-div')
const nav = document.getElementById('nav')

astro.addEventListener('click', function (){
    astro.classList.toggle('moon')
    topo.classList.toggle('craters')
    topLeft.classList.toggle('craters')
    topRight.classList.toggle('craters')
    bottom.classList.toggle('craters')
    bottomLeft.classList.toggle('craters')
    bottomRight.classList.toggle('craters')
   
    topLeft.classList.toggle('medium')
    topRight.classList.toggle('big')
    bottom.classList.toggle('small')

    topo.classList.toggle('invisible')
    bottomLeft.classList.toggle('invisible')
    bottomRight.classList.toggle('invisible')
    button.classList.toggle('deepSky')

    logo.classList.toggle('green-color')
    abouth1.classList.toggle('green-color')
    abouth2.classList.toggle('green-color')
    contacth1.classList.toggle('green-color')
    hardh1.classList.toggle('green-color')
    about.classList.toggle('green-color')
    contact.classList.toggle('green-color')
    habilidades.classList.toggle('green-color')

    line1.classList.toggle('green-background')
    line2.classList.toggle('green-background')
    line3.classList.toggle('green-background')
    nav.classList.toggle('darkest-background')

    body.classList.toggle('dark-background')
    body.classList.toggle('white-color')
    header.classList.toggle('darkest-background')
    header.classList.toggle('white-border-bottom')
    footer.classList.toggle('darkest-background')
    footer.classList.toggle('white-border-top')

    links.forEach(function (link){
        link.classList.toggle('white-color')
    })

    local.classList.toggle('green-local')
    phone.classList.toggle('green-phone')
    mail.classList.toggle('green-mail')
    linkedin.classList.toggle('green-linkedin')
    github.classList.toggle('green-github')
    instagram.classList.toggle('green-instagram')
})

menuhamburguer.addEventListener('click', function (){
    line1.classList.toggle('rotete-rigth')
    line3.classList.toggle('rotate-left')
    line2.classList.toggle('invisible')
    menuhamburguer.classList.toggle('remove-height')
    navegacao.classList.toggle('show-menu')
})